version: v1

rootPackage: bingo

directory:
  cmd: internal/bingoctl/cmd
  model: internal/apiserver/model
  store: internal/apiserver/store
  biz: internal/apiserver/biz
  controller: internal/apiserver/http/controller/v1
  middleware: internal/apiserver/http/middleware
  request: internal/apiserver/http/request/v1
  job: internal/watcher/watcher
  migration: internal/bingoctl/database/migration
  seeder: internal/bingoctl/database/seeder

registries:
  router: internal/apiserver/router/api.go
  store:
    filePath: internal/apiserver/store/store.go
    interface: "IStore"
  biz:
    filePath: internal/apiserver/biz/biz.go
    interface: "IBiz"

mysql:
  host: 127.0.0.1:3306
  username: root
  password:
  database: bingo
