version: v1

rootPackage: bingo

directory:
  cmd: internal/bingoctl/cmd
  model: internal/pkg/model
  store: internal/pkg/store
  biz: internal/apiserver/biz
  handler: internal/apiserver/handler/http
  middleware: internal/pkg/middleware/http
  request: pkg/api/apiserver/v1
  migration: internal/pkg/database/migration
  seeder: internal/pkg/database/seeder

registries:
  router: internal/apiserver/router/api.go
  store:
    filePath: internal/pkg/store/store.go
    interface: "IStore"
  biz:
    filePath: internal/apiserver/biz/biz.go
    interface: "IBiz"

mysql:
  host: 127.0.0.1:3306
  username: root
  password:
  database: bingo

# Migration configuration (optional)
migrate:
  table: bingo_migration  # Migration records table name, default: bingo_migration
