version: "2"
run:
  concurrency: 4
  allow-parallel-runners: true
linters:
  default: none
  enable:
    # - errcheck
    # - staticcheck
    - govet
    # - ineffassign
    - unused
    - nlreturn
  settings:
    nlreturn:
      block-size: 1
issues:
  fix: true
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bingo-project/bingo/)
        - blank
        - dot
      custom-order: false
